[project]
name = "prod-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.12",
    "chromadb>=0.5",
    "cohere>=5",
    "fastapi>=0.115",
    "jq>=1.11.0",
    "langchain>=0.3",
    "langchain-anthropic>=0.2",
    "langchain-community>=0.3",
    "langchain-core>=0.3",
    "langchain-google-genai>=4.2.3",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=0.2",
    "langgraph>=0.2",
    "langgraph-checkpoint>=0.1",
    "langgraph-checkpoint-sqlite>=0.1",
    "langsmith>=0.1",
    "pydantic>=2.7",
    "pydantic-settings>=2.3",
    "pypdf>=4",
    "python-dotenv>=1.0",
    "rank-bm25>=0.2",
    "tenacity>=8",
    "tiktoken>=0.7",
    "unstructured>=0.15",
    "uvicorn[standard]>=0.30",
]

